# -*- coding: utf-8 -*-
"""Untitled73.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WdtWOUAH73-we80xCz8xIkfCyj97MkGe
"""

!pip install arch -q
!pip install ecos -q
!pip install python-bcb -q
!pip install yfinance -q
!pip install statsmodels -q

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import skew, kurtosis
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.stattools import adfuller
import warnings
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.graphics.tsaplots import plot_acf
import matplotlib.pyplot as plt
from arch import arch_model
import cvxpy as cp
from statsmodels.tsa.regime_switching.markov_regression import MarkovRegression
import statsmodels.api as sm

"""**FUNDO HEDGE FUND, ANALISE QUANTI MACRO E LOCAL COM TECTICAS AVANÇADAS RISCO, Arima, Garch, backtest, derivativo, monte carlos, markwids e regressao!

drawdon do potifolio:-0.1607

** Rentabilidade**
Portfólio Dinâmico: 23.07%
IBOV: 5.90%
S&P 500: 13.70%
CDI: 9.91%

"""

combined_close_prices = pd.DataFrame()
assets = [ 'JPM', 'AAPL','MU','BTC-USD','AMZN','REMX','GLD']

for asset in assets:
    data = yf.download(asset, start='2020-01-01', end='---')
    combined_close_prices[asset] = data['Close']
    acao=yf.download(asset,period='7y')
    plt.figure(figsize=(12,5))
    plt.plot(acao['Close'])
    plt.show()

assets = [ 'JPM', 'AAPL','MU','BTC-USD','AMZN','REMX','GLD']

prices = yf.download(assets, start='2020-01-01', end='2026-07-01')['Close']
if isinstance(prices.index, pd.PeriodIndex): #convert to timestamp
    prices.index = prices.index.to_timestamp()
returns = prices.pct_change().dropna() #daily returns in decimal
returns_pct = returns * 100 #convert to percentage
print(returns.isnull().sum())#missing values
returns = returns.ffill()#forward fill missing values
summary = returns.describe().T
print(summary)#summary statistics
prices.plot(figsize=(10,5), title='Close Prices')
plt.show()#plot price
returns.plot(figsize=(10,5), title='Daily Returns')
plt.show()#plot return

returns = returns.dropna()
print('Return skewness:',returns.skew())
print('Return kurtosis:',returns.kurtosis())
if isinstance(returns.index, pd.PeriodIndex):
    returns.index = returns.index.to_timestamp()
for col in returns.columns: #return distributions
    plt.figure(figsize=(6,4))
    sns.histplot(returns[col], bins=50, kde=True, color='skyblue')
    plt.title(f'Return Distribution: {col}')
    plt.xlabel('Daily Returns (%)')
    plt.ylabel('Frequency')
    plt.show()

fig, axes = plt.subplots(1,2, figsize=(12,4)) #autocorrelation and partial autocorrelation
plot_acf(returns['AMZN'], lags=30, ax=axes[0], title='Amazon ACF')
plot_pacf(returns['AMZN'], lags=30, ax=axes[1], title='Amazon PACF')
plt.show()

returns['AMZN'].plot(figsize=(10,4), title='Daily Returns: Amazon')#volatility Clustering Observation for Tesla(Highest volatility among assets)
plt.xlabel('Date')
plt.ylabel('Daily Return (%)')
plt.show()

hist_corr = returns.loc[:'2020'].corr()#correlation heatmap
plt.figure(figsize=(8,6))
sns.heatmap(hist_corr, annot=True, cmap='coolwarm', vmin=-1, vmax=1)
plt.title("Correlation Heatmap of Asset Returns")
plt.show()

#comparando assets com benchmark "S&P500"
assets = [ 'JPM', 'AAPL','MU','BTC-USD','AMZN','REMX']

benchmark = '^GSPC'
prices = yf.download(assets, start='2020-01-01', end='2026-07-01')['Close']
benchmark = '^GSPC'
periodo = '8y'
benchmark_data = yf.download(benchmark, period=periodo)
if isinstance(prices.index, pd.PeriodIndex):
    prices.index = prices.index.to_timestamp()
    benchmark_data.index = benchmark_data.index.to_timestamp()

# Calcular retornos diários s&p500 e assets
returns = prices.pct_change().dropna()
benchmark_returns = benchmark_data['Close'].pct_change().dropna()

returns_pct = returns * 100
benchmark_returns_pct = benchmark_returns * 100

plt.figure(figsize=(10, 5))
plt.plot(returns_pct.index, returns_pct['MU'], label='Micron')
plt.plot(returns_pct.index, returns_pct['AAPL'], label='Apple')
plt.plot(returns_pct.index, returns_pct['REMX'], label='etf terras raras')
plt.plot(returns_pct.index, returns_pct['JPM'], label='JPMorgan')
plt.plot(returns_pct.index, returns_pct['BTC-USD'], label='Bitcoin')
plt.plot(returns_pct.index, returns_pct['AMZN'], label='Amazon')

plt.plot(benchmark_returns_pct.index, benchmark_returns_pct, label='S&P500', linestyle='--')
plt.title('Daily Returns of Assets vs S&P500')
plt.xlabel('Date')
plt.ylabel('Daily Return (%)')
plt.legend()
plt.show()

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

#comparando assets com benchmark "S&P500" grafico de disperção
assets = [ 'JPM', 'AAPL','MU','BTC-USD','AMZN','REMX','GLD']

benchmark = '^GSPC'

# Download data for assets
prices = yf.download(assets, start='2020-01-01', end='2026-07-01')['Close']

# Download data for benchmark (S&P500)
# Using start/end dates for consistency with asset data, instead of 'period'
benchmark_data = yf.download(benchmark, start='2020-01-01', end='2026-06-01')['Close']

if isinstance(prices.index, pd.PeriodIndex):
    prices.index = prices.index.to_timestamp()
    benchmark_data.index = benchmark_data.index.to_timestamp()

# Calcular retornos diários s&p500 e assets
returns = prices.pct_change()
benchmark_returns = benchmark_data.pct_change()

# Combine and drop NaN values to ensure common date range
# This aligns the indices of both dataframes
combined_returns = pd.concat([returns, benchmark_returns], axis=1).dropna()

# Separate the aligned returns
returns_aligned = combined_returns.iloc[:, :-1] # All columns except the last one (benchmark)
benchmark_returns_aligned = combined_returns.iloc[:, -1] # The last column (benchmark)

returns_pct = returns_aligned * 100
benchmark_returns_pct = benchmark_returns_aligned * 100 # Corrected to *100 for consistency

plt.figure(figsize=(10, 4))
plt.scatter(benchmark_returns_pct, returns_pct['MU'], label='Micron')
plt.scatter(benchmark_returns_pct, returns_pct['AAPL'], label='Apple')
plt.scatter(benchmark_returns_pct, returns_pct['REMX'], label='Etf-terras raras')
plt.scatter(benchmark_returns_pct, returns_pct['JPM'], label='JPMorgan')
plt.scatter(benchmark_returns_pct, returns_pct['BTC-USD'], label='Bitcoin')
plt.scatter(benchmark_returns_pct, returns_pct['AMZN'], label='Amazon')
plt.scatter(benchmark_returns_pct, returns_pct['GLD'], label='etf ouro')
plt.scatter(benchmark_returns_pct, benchmark_returns_pct, label='S&P500', linestyle='--')

plt.title('Daily Returns of Assets vs S&P500')
plt.xlabel('S&P500 Daily Return (%)')
plt.ylabel('Asset Daily Return (%)')
plt.legend()
plt.show()

"""### indice de Sharpe d cada ativo
 métricas:

 **Retorno Médio Diário**: A média dos retornos diários de cada ativo.
  **Desvio Padrão Diário (Volatilidade)**: O desvio padrão dos retornos diários de cada ativo.
  **Taxa Livre de Risco**: Para simplificar, usaremos 0% para o cálculo diário, mas em um cenário real, você usaria a taxa de um ativo sem risco (como títulos do tesouro). Uma taxa anualizada pode ser convertida para diária. Para o Sharpe Ratio anualizado, multiplicaremos o Sharpe Ratio diário pela raiz quadrada do número de dias de negociação em um ano (geralmente 252).
"""

# Calculate daily average returns
daily_avg_returns = returns_aligned.mean()

# Calculate daily standard deviation (volatility)
daily_std_dev = returns_aligned.std()

# Assuming a risk-free rate of 2% per year
annual_risk_free_rate = 0.02
# Convert annual risk-free rate to daily rate (assuming 252 trading days)
risk_free_rate_daily = (1 + annual_risk_free_rate)**(1/252) - 1

# Calculate daily Sharpe Ratio
daily_sharpe_ratio = (daily_avg_returns - risk_free_rate_daily) / daily_std_dev

# Annualize Sharpe Ratio (assuming 252 trading days in a year)
annualized_sharpe_ratio = daily_sharpe_ratio * np.sqrt(252)

# Create a DataFrame to display the risk metrics
risk_metrics = pd.DataFrame({
    'Daily Average Return': daily_avg_returns,
    'Daily Volatility (Std Dev)': daily_std_dev,
    'Daily Sharpe Ratio': daily_sharpe_ratio,
    'Annualized Sharpe Ratio': annualized_sharpe_ratio
})

print("Métricas de Risco por Ativo (com taxa livre de risco de 2% ao ano):")
display(risk_metrics.sort_values(by='Annualized Sharpe Ratio', ascending=False))

"""### Desempenho Acumulado dos Ativos e Benchmark

Vamos visualizar o desempenho acumulado de cada ativo e do S&P500 desde o início do período.
"""

# Calculate cumulative returns for assets
cumulative_returns = (1 + returns_aligned).cumprod() - 1

# Calculate cumulative returns for the benchmark
cumulative_benchmark_returns = (1 + benchmark_returns_aligned).cumprod() - 1

plt.figure(figsize=(14, 7))

# Plot cumulative returns for each asset
for column in cumulative_returns.columns:
    plt.plot(cumulative_returns.index, cumulative_returns[column], label=column)

# Plot cumulative returns for the benchmark
plt.plot(cumulative_benchmark_returns.index, cumulative_benchmark_returns, label='S&P500', linestyle='--')

plt.title('Cumulative Performance of Assets vs S&P500 (Since 2020)')
plt.xlabel('Date')
plt.ylabel('Cumulative Return')
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend()
plt.tight_layout()
plt.show()

"""### Visualização da Matriz de Correlação

Vamos visualizar a matriz de correlação dos retornos dos ativos usando um mapa de calor (`heatmap`). Isso nos ajuda a entender as relações entre os movimentos dos preços dos diferentes ativos.
"""

import scipy.stats as stats

# Portafolio equiponderado
ret_port = returns_aligned.mean(axis=1)
capital = 1_000_000  # USD
nivel_confianza = 0.95

# VaR Histórico
var_hist = np.percentile(ret_port, (1 - nivel_confianza) * 100)
cvar_hist = ret_port[ret_port <= var_hist].mean()

# VaR Paramétrico (Normal)
mu_port = ret_port.mean()
sigma_port = ret_port.std()
var_param = stats.norm.ppf(1 - nivel_confianza, mu_port, sigma_port)
cvar_param = mu_port - sigma_port * stats.norm.pdf(stats.norm.ppf(1 - nivel_confianza)) / (1 - nivel_confianza)

# Monte Carlo — 10,000 escenarios
np.random.seed(42)
n_mc = 10000
n_dias = 252
ret_mc = np.random.normal(mu_port, sigma_port, (n_mc, n_dias))
valor_final = capital * np.prod(1 + ret_mc, axis=1)
var_mc = np.percentile(valor_final, (1 - nivel_confianza) * 100)
cvar_mc = valor_final[valor_final <= var_mc].mean()

#plot monte carlos
plt.figure(figsize=(12, 6))
plt.hist(valor_final, bins=50, alpha=0.7, label='Monte Carlo Simulation')
plt.axvline(x=var_hist, color='red', linestyle='--', label=f'VaR Histórico ({100 * nivel_confianza:.2f}%)')
plt.axvline(x=var_param, color='green', linestyle='--', label=f'VaR Normal ({100 * nivel_confianza:.2f}%)')
plt.axvline(x=var_mc, color='blue', linestyle='--', label=f'VaR Monte Carlo ({100 * nivel_confianza:.2f}%)')
plt

# Evolução do portfólio no cenário de Monte Carlo

# Calcular o valor do portfólio ao longo do tempo para todos os cenários
# capital * (1 + ret_mc) vai expandir o capital para cada retorno.
# .cumprod(axis=1) calcula o produto cumulativo ao longo do tempo (dias) para cada cenário.
# Isso resultará em um DataFrame onde cada linha é um cenário e as colunas são a evolução diária.
portfolio_evolution_all_scenarios = capital * (1 + ret_mc).cumprod(axis=1)

# Calcular a média da evolução do portfólio em todos os cenários
average_portfolio_evolution = portfolio_evolution_all_scenarios.mean(axis=0)

# Criar um índice de datas para o plot
# Assumindo que o `ret_mc` representa dias consecutivos após a última data do `returns_aligned`
last_date = returns_aligned.index[-1]
dates = pd.date_range(start=last_date + pd.Timedelta(days=1), periods=n_dias)

plt.figure(figsize=(12, 6))
plt.plot(dates, average_portfolio_evolution, label='Portfólio Médio (Cenários MC)', color='purple')
plt.title('Evolução Média do Valor do Portfólio em Cenários Monte Carlo')
plt.xlabel('Data')
plt.ylabel('Valor do Portfólio (USD)')
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend()
plt.tight_layout()
plt.show()

"""RESIDUOS COM ARIMA DE CADA ATIVOS"""

warnings.filterwarnings("ignore")
assets = returns.columns
arima_models = {}
arima_residuals = {}
arima_forecasts = {}
acf_assets = ['AMZN', 'ORCL']
for asset in assets:
    arima_model = ARIMA(returns[asset], order=(1,0,1)).fit()#fit ARIMA(1,0,1)
    arima_models[asset] = arima_model
    print(f"ARIMA(1,0,1) Summary for {asset}")
    print(arima_model.summary())
    residuals = arima_model.resid #residuals
    arima_residuals[asset] = residuals

    plt.figure(figsize=(10,4)) #plot residuals
    plt.plot(residuals)
    plt.title(f'{asset} ARIMA Residuals')
    plt.xlabel('Date')
    plt.ylabel('Residual')
    plt.show()

"""### Q-Q Plot dos Resíduos ARIMA para Verificação de Normalidade

Vamos usar Q-Q plots para comparar a distribuição dos resíduos do modelo ARIMA com uma distribuição normal teórica. Se os pontos se alinharem aproximadamente com a linha, isso sugere que os resíduos seguem uma distribuição normal.
"""

import statsmodels.api as sm
import matplotlib.pyplot as plt
import warnings
from statsmodels.tsa.arima.model import ARIMA
import pandas as pd # Ensure pandas is imported as it's used by returns

warnings.filterwarnings("ignore")

# Ensure 'returns' DataFrame is available from previous cells. Assuming it is from cell 'Bb3olrbW8iWP'.
# If 'returns' is not defined, this code will still fail.
# For robustness, we could explicitly re-import/re-calculate returns if needed, but assuming existing flow.

assets = returns.columns
arima_models = {}
arima_residuals = {}
arima_forecasts = {} # Initialized for consistency, though not used for Q-Q plots directly

for asset in assets:
    # Fit ARIMA(1,0,1) model for each asset
    arima_model = ARIMA(returns[asset], order=(1,0,1)).fit()
    arima_models[asset] = arima_model
    # print(f"ARIMA(1,0,1) Summary for {asset}") # Commented out to reduce output verbosity
    # print(arima_model.summary()) # Commented out to reduce output verbosity

    # Get residuals
    residuals = arima_model.resid
    arima_residuals[asset] = residuals

    # Plot residuals (optional, as the request is for Q-Q plots)
    # plt.figure(figsize=(10,4))
    # plt.plot(residuals)
    # plt.title(f'{asset} ARIMA Residuals')
    # plt.xlabel('Date')
    # plt.ylabel('Residual')
    # plt.show()

    # Forecast (optional, not directly related to Q-Q plot request)
    # forecast = arima_model.get_forecast(steps=5)
    # forecast_mean = forecast.predicted_mean
    # forecast_ci = forecast.conf_int()
    # arima_forecasts[asset] = {'mean': forecast_mean, 'ci': forecast_ci}
    # print(f"Next 5-day forecast for {asset}:")
    # print(forecast_mean)
    # print(forecast_ci)

# Now, generate Q-Q plots using the populated arima_residuals
for asset, residuals in arima_residuals.items():
    if not residuals.empty:
        fig = plt.figure(figsize=(8, 6))
        sm.qqplot(residuals, line='s', ax=plt.gca())
        plt.title(f'Q-Q Plot dos Resíduos ARIMA para {asset}')
        plt.xlabel('Quantis Teóricos (Normal)')
        plt.ylabel('Quantis dos Resíduos')
        plt.grid(True, linestyle='--', alpha=0.7)
        plt.show()
    else:
        print(f"Nenhum resíduo encontrado para {asset}")

warnings.filterwarnings("ignore")
assets = returns.columns
arima_models = {}
arima_residuals = {}
arima_forecasts = {}
acf_assets = ['AMZN', 'ORCL']
for asset in assets:
    arima_model = ARIMA(returns[asset], order=(1,0,1)).fit()#fit ARIMA(1,0,1)
    arima_models[asset] = arima_model
    print(f"ARIMA(1,0,1) Summary for {asset}")
    print(arima_model.summary())
    residuals = arima_model.resid #residuals
    arima_residuals[asset] = residuals
    plt.figure(figsize=(10,4)) #plot residuals
    plt.plot(residuals)
    plt.title(f'{asset} ARIMA Residuals')
    plt.xlabel('Date')
    plt.ylabel('Residual')
    plt.show()

    forecast = arima_model.get_forecast(steps=5) #return forecast for next 5 days
    forecast_mean = forecast.predicted_mean
    forecast_ci = forecast.conf_int()
    arima_forecasts[asset] = {'mean': forecast_mean, 'ci': forecast_ci}
    print(f"Next 5-day forecast for {asset}:")
    print(forecast_mean)
    print(forecast_ci)

"""USANDO FORCAST GARCH NO TREINO-RETORNO-MCOVARIANCIA"""

ms_garch_models = {}
ms_garch_fitted_vol = pd.DataFrame(index=returns.index, columns=returns.columns, dtype=float)
ms_garch_forecasts = {}
regime_prob_df = pd.DataFrame(index=returns.index, columns=returns.columns, dtype=float)
forecast_horizon = 6 #forecast for the next 10 days
TRADING_DAYS = 252
for asset in returns.columns:
    r = returns[asset].dropna()  # decimal returns
    mr = MarkovRegression(r, k_regimes=2, trend='c', switching_variance=True) #fit Markov switching model (2 regimes)
    mr_res = mr.fit(disp=False)
    smoothed_p = mr_res.smoothed_marginal_probabilities[1]  #prob of regime 1 (high vol)
    regime_prob_df.loc[smoothed_p.index, asset] = smoothed_p.values
    high_idx = smoothed_p[smoothed_p > 0.5].index #separate observations by regime
    low_idx = smoothed_p[smoothed_p <= 0.5].index
    high_r = r.loc[high_idx]
    low_r = r.loc[low_idx]

    def try_garch(series):    #fit GARCH on each regime

        if len(series) < 30:
            return None
        am = arch_model(series * 100, vol='Garch', p=1, q=1, mean='constant', dist='normal')  #scale to percent for arch
        return am.fit(disp='off')

    garch_high = try_garch(high_r)
    garch_low = try_garch(low_r)

    ms_garch_models[asset] = {'mr_res': mr_res, 'garch_high': garch_high, 'garch_low': garch_low}

    vol_series = pd.Series(index=r.index, dtype=float) #build fitted volatility series (decimal)
    if garch_high is not None:
        cv_high = pd.Series(garch_high.conditional_volatility, index=high_r.index)
        vol_series.loc[high_r.index] = cv_high / 100 #convert percent same as ones got from arch
    if garch_low is not None:
        cv_low = pd.Series(garch_low.conditional_volatility, index=low_r.index)
        vol_series.loc[low_r.index] = cv_low / 100

    ms_garch_fitted_vol[asset].loc[vol_series.index] = vol_series

    #forecast combined volatility for forecast_horizon days

    last_prob_high = smoothed_p.iloc[-1]
    if (garch_high is not None) and (garch_low is not None):
        fh_high = garch_high.forecast(horizon=forecast_horizon, reindex=False).variance.values[-1, :]
        fh_low  = garch_low.forecast(horizon=forecast_horizon, reindex=False).variance.values[-1, :]
        combined_var = last_prob_high * (fh_high / 100.0**2) + (1 - last_prob_high) * (fh_low / 100.0**2)  #variance is in percent^2 convert to decimal vol

        forecast_vol = np.sqrt(combined_var)  #decimal vol per day

    ms_garch_forecasts[asset] = forecast_vol  #decimal vol (per day) for horizon
    print(f"{asset} forecast vol (day {forecast_horizon}):", forecast_vol[-1])

#build covariance matrix from latest forecasted vol
last_vol = pd.Series({asset: ms_garch_forecasts[asset][-1] if asset in ms_garch_forecasts else np.nan for asset in returns.columns})
last_vol = last_vol.astype(float)
last_vol_annual = last_vol * np.sqrt(TRADING_DAYS)

#use historical correlation to pair with forecast vol
hist_corr = returns.corr().fillna(0).values  # numpy matrix
outer = np.outer(last_vol_annual.values, last_vol_annual.values)
cov_matrix = outer * hist_corr
print("\nCovariance Matrix (Assets):")
plt.figure(figsize=(10, 8))
sns.heatmap(cov_matrix, annot=True, fmt=".6f", cmap="YlGnBu",
            xticklabels=returns.columns, yticklabels=returns.columns)
plt.title("Asset Returns Covariance Matrix")
plt.show()

asset_a = 'AMZN'
r = returns[asset_a].dropna()
vol = ms_garch_fitted_vol[asset_a].dropna()
prob_high = regime_prob_df[asset_a].dropna()

fig, ax1 = plt.subplots(figsize=(14, 6)) #apple returns and regime probability


ax1.plot(r.index, r, color='grey', alpha=0.6, label='Daily Returns')
ax1.set_ylabel('Returns', color='grey')
ax1.set_title(f'{asset} Returns and High-Volatility Regime Probability')

ax2 = ax1.twinx()
ax2.plot(prob_high.index, prob_high, color='red', label='P(High Vol Regime)')
ax2.fill_between(prob_high.index, 0, prob_high, color='red', alpha=0.3)
ax2.set_ylabel('Regime Probability', color='red')
ax2.set_ylim(0, 1)

ax1.legend(loc='upper left')
ax2.legend(loc='upper right')
plt.show()

plt.figure(figsize=(14, 6)) #fitted conditional volatility (MS-GARCH)
plt.plot(vol.index, vol, label='Fitted Volatility (daily)', color='blue')
plt.title(f'{asset} MS-GARCH Fitted Conditional Volatility')
plt.ylabel('Volatility')
plt.xlabel('Date')
plt.legend()
plt.show()

mean_returns = returns.mean() * TRADING_DAYS   # annual mean in decimals
cov_matrix = returns.cov() * TRADING_DAYS  # annual covariance in decimals






target_return = 0.21  # target return in decimals
min_w = 0.05
max_w = 0.35
portfolio_value = 100000 #initial investment as 100,000$
import cvxpy as cp
n = len(returns.columns)
w = cp.Variable(n)
port_return = mean_returns.values @ w
port_var = cp.quad_form(w, cov_matrix)

constraints = [cp.sum(w) == 1, w >= min_w , w <= max_w]

prob = cp.Problem(cp.Minimize(port_var), constraints)
result = prob.solve(solver=cp.OSQP, verbose=False)
weights_opt = pd.Series(w.value, index=returns.columns)
weights_opt = weights_opt / weights_opt.sum() #normalize small numerical errors
print('')
print("Optimal weights (fixed):")
print(weights_opt)

# Compute static portfolio metrics
rf_data = yf.download("^IRX", start="2020-01-01", end="2026-01-01")['Close']
Rf = float(rf_data.iloc[-1]) / 100  # convert from percentage to decimal
portfolio_var = float(weights_opt.values.T @ cov_matrix @ weights_opt.values)
portfolio_std = np.sqrt(portfolio_var)
achieved_return = float(mean_returns.values @ weights_opt.values)
achieved_sharpe = (achieved_return - Rf) / portfolio_std

print("\nStatic Portfolio Metrics:")
print('risk free rate is', Rf)
print('achieved portfolio return', achieved_return)
print('achieved portfolio volatility', portfolio_std)
print('achieved portfolio Sharpe ratio', achieved_sharpe)

benchmark_data = yf.download("^GSPC", start="2020-01-01", end="2026-01-01")['Close']
benchmark_returns = benchmark_data.pct_change().dropna()

annual_return_benchmark = benchmark_returns.mean() * 252
annualized_vol_benchmark = benchmark_returns.std() * np.sqrt(252)
sharpe_benchmark = (annual_return_benchmark - Rf) / annualized_vol_benchmark

print("\nBenchmark Metrics (S&P 500):")
print("Annual Return:", round(annual_return_benchmark.item(), 4))
print("Annualized Volatility:", round(annualized_vol_benchmark.item(), 4))
print("Sharpe Ratio:", round(sharpe_benchmark.item(), 4))

# Build dynamic weights using per-asset regime_prob_df
# dynamic rule: base_weights * (1 - lambda_scale * prob_high) then normalize
lambda_scale = 0.5
base_weights = weights_opt.copy()
regime_prob_df = regime_prob_df.fillna(0.0)# fill missing probs with 0.0


dynamic_weights = (base_weights.values * (1 - lambda_scale * regime_prob_df.values))
dynamic_weights_df = pd.DataFrame(dynamic_weights, index=regime_prob_df.index, columns=regime_prob_df.columns)# convert back to DataFrame
dynamic_weights_df = dynamic_weights_df.div(dynamic_weights_df.sum(axis=1), axis=0).fillna(method='ffill').fillna(1.0 / n) # normalize rows

weights_shifted = dynamic_weights_df.shift(1).dropna() # shift weights to avoid lookahead since weights computed from info at t are applied to returns at t+1
aligned_returns = returns.loc[weights_shifted.index, weights_shifted.columns]

portfolio_returns_dynamic = (aligned_returns * weights_shifted).sum(axis=1)


tc = 0.001 #transaction costs
weight_changes = weights_shifted.diff().abs().fillna(0)
trade_costs = (weight_changes.sum(axis=1) * portfolio_value * tc) / portfolio_value  # fraction of portfolio
portfolio_returns_dynamic = portfolio_returns_dynamic - trade_costs
cumulative_portfolio = (1 + portfolio_returns_dynamic).cumprod()
print('net achieved return with dynamic weights(transaction costs excluded , 2020-2026):', cumulative_portfolio.iloc[-1])

num_portfolios = 5000 #generate random portfolios to plot the efficient frontier
results = np.zeros((3, num_portfolios))
weights_record = []

for i in range(num_portfolios):
    weights = np.random.random(len(mean_returns))
    weights /= np.sum(weights)
    weights_record.append(weights)

    port_return = np.dot(weights, mean_returns)
    port_vol = np.sqrt(np.dot(weights.T, np.dot(cov_matrix, weights)))
    sharpe = (port_return - Rf) / port_vol

    results[0, i] = port_vol
    results[1, i] = port_return
    results[2, i] = sharpe

plt.figure(figsize=(10, 6)) #efficient frontier
plt.scatter(results[0, :], results[1, :], c=results[2, :], cmap='viridis', s=15)
plt.colorbar(label='Sharpe Ratio')
plt.scatter(portfolio_std, achieved_return, color='red', s=100, marker='*', label='Optimal Portfolio')
plt.title("Efficient Frontier with Optimal Portfolio")
plt.xlabel("Annualized Volatility")
plt.ylabel("Expected Annual Return")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 5)) #optimal weights
plt.bar(mean_returns.index, weights_opt, color='skyblue')
plt.title("Optimal Portfolio Weights (Markowitz Optimization)")
plt.xlabel("Assets")
plt.ylabel("Weight Allocation")
plt.xticks(rotation=45)
plt.grid(axis='y')
plt.show()

plt.figure(figsize=(10, 6)) #risk vs return per asset
asset_vols = np.sqrt(np.diag(cov_matrix))
plt.scatter(asset_vols, mean_returns, c='gray', s=50)
for i, asset in enumerate(mean_returns.index):
    plt.text(asset_vols[i], mean_returns[i], asset, fontsize=9, ha='right')
plt.scatter(portfolio_std, port_return, color='red', s=100, marker='*', label='Optimal Portfolio')
plt.title("Individual Assets vs. Optimal Portfolio")
plt.xlabel("Volatility ")
plt.ylabel("Expected Return")
plt.legend()
plt.grid(True)
plt.show()

rf_data = yf.download("^IRX", start="2020-01-01", end="2026-01-01")['Close'] #risk free rate as 3 month US treasury
Rf = float(rf_data.iloc[-1]) / 100  # convert from percentage to decimal

tickers = list(assets) #backtest data
backtest_data = yf.download(tickers, start="2020-01-01", end="2026-01-01")['Close']
backtest_returns = backtest_data.pct_change().dropna()

regime_prob_bt = pd.DataFrame(index=backtest_returns.index, columns=assets) #regime probabilities
for asset in assets:
    returns_series = backtest_returns[asset].dropna()
    model = MarkovRegression(returns_series, k_regimes=2, trend='c', switching_variance=True)
    ms_fit = model.fit(disp=False)
    regime_prob_bt.loc[returns_series.index, asset] = ms_fit.smoothed_marginal_probabilities[1]

dynamic_weights_bt = pd.DataFrame(index=backtest_returns.index, columns=assets) #dynamic weights
for t in backtest_returns.index:
    high_vol_prob = regime_prob_bt.loc[t]
    dynamic_weights_bt.loc[t] = base_weights * (1 - lambda_scale * high_vol_prob)

dynamic_weights_bt = dynamic_weights_bt.div(dynamic_weights_bt.sum(axis=1), axis=0)#normalize weights


weights_shifted = dynamic_weights_bt.shift(1).dropna() #shift weights to avoid look ahead bias
backtest_returns = backtest_returns.loc[weights_shifted.index]
weights_shifted = weights_shifted.div(weights_shifted.sum(axis=1), axis=0)

portfolio_returns_dynamic_raw = (backtest_returns * weights_shifted).sum(axis=1) #dynamic portfolio returns

# Ensure portfolio_returns_dynamic is numeric and handle initial NaNs
portfolio_returns_dynamic_raw = pd.to_numeric(portfolio_returns_dynamic_raw, errors='coerce')
# Drop any leading NaNs that might result from alignment or shifting
portfolio_returns_dynamic = portfolio_returns_dynamic_raw.dropna()

tc = 0.001  # 0.1% as transaction costs
portfolio_value = 100000  # initial capital
weight_diff = dynamic_weights_bt.diff().fillna(0)
transaction_costs = (weight_diff.abs() * portfolio_value * tc).sum(axis=1)

# Align transaction_costs to portfolio_returns_dynamic index before subtraction
transaction_costs = transaction_costs.reindex(portfolio_returns_dynamic.index).fillna(0)

portfolio_returns_dynamic = portfolio_returns_dynamic - transaction_costs / portfolio_value

#performance metrics

dynamic_return_bt = portfolio_returns_dynamic.mean() * 252
annualized_vol_bt = portfolio_returns_dynamic.std() * np.sqrt(252)
sharpe_bt = (dynamic_return_bt - Rf) / annualized_vol_bt

print("\nBacktest Metrics (Dynamic Regime-Adjusted Portfolio):")
print("Annual Return:", round(dynamic_return_bt, 4))
print("Annualized Volatility:", round(annualized_vol_bt, 4))
print("Sharpe Ratio:", round(sharpe_bt, 4))

benchmark_data = yf.download("^GSPC", start="2020-01-01", end="2026-01-01")['Close']
benchmark_returns = benchmark_data.pct_change().dropna()
# Align benchmark_returns to the index of portfolio_returns_dynamic
benchmark_returns = benchmark_returns.reindex(portfolio_returns_dynamic.index).fillna(0)

annual_return_benchmark = benchmark_returns.mean() * 252
annualized_vol_benchmark = benchmark_returns.std() * np.sqrt(252)
sharpe_benchmark = (annual_return_benchmark - Rf) / annualized_vol_benchmark

print("\nBenchmark Metrics (S&P 500):")
print("Annual Return:", round(annual_return_benchmark.item(), 4))
print("Annualized Volatility:", round(annualized_vol_benchmark.item(), 4))
print("Sharpe Ratio:", round(sharpe_benchmark.item(), 4))

cumulative_portfolio = (1 + portfolio_returns_dynamic).cumprod() #cumulative returns
cumulative_benchmark = (1 + benchmark_returns).cumprod()

print("\nCumulative Portfolio Return (Growth of $1):", round(cumulative_portfolio.iloc[-1], 4))
print("Cumulative Benchmark Return (Growth of $1):", round(cumulative_benchmark.iloc[-1], 4))

plt.figure(figsize=(10, 6)) #plot results
plt.plot(cumulative_portfolio, label="Dinamica do Portfolio", linewidth=2)
plt.plot(cumulative_benchmark, label="S&P 500 (Benchmark)", linestyle="--", color="gray")
plt.title("Retorno acumulado: Dinamic Regime-Ajustad Portfolio vs. S&P 500 (2020–2026)")
plt.xlabel("Date")
plt.ylabel("Retorno acumulad (Growth of $1)")
plt.legend()
plt.grid(True)
plt.show()



"""***Dados backtest portifolio ajustado***

retorno anual:0,2446

volatilidade anualizada:0,1837

sharpe:1,2409

***benchmark s&p500***

retorno anual:0,2281

volatilidade anual:0,1539

sharp:1,2409

***retorno cumulado***

portifolio:1,8218

benchmark:1,7696

PLOTANDO O PESO D CADA ATIVO NO BACKTEST, DE FORMA QUE OS PESOS FORAM AJUSTADO DE ACORDO COM A VOLATILIDADE NA DINAMICA DO PORTIFOLIO
"""

plt.figure(figsize=(14, 7))
for column in dynamic_weights_bt.columns:
    plt.plot(dynamic_weights_bt.index, dynamic_weights_bt[column], label=column)

plt.title('Evolução dos Pesos Dinâmicos do Portfólio ao Longo do Tempo (Backtest)')
plt.xlabel('Data')
plt.ylabel('Alocação de Peso')
plt.legend(loc='upper left')
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

cumulative_portfolio = (1 + portfolio_returns_dynamic).cumprod()
cumulative_benchmark = (1 + benchmark_returns).cumprod()

# Calculate daily peak for dynamic portfolio
previous_peaks_portfolio = cumulative_portfolio.expanding().max()
drawdown_portfolio = (cumulative_portfolio / previous_peaks_portfolio) - 1

# Calculate daily peak for S&P 500
previous_peaks_benchmark = cumulative_benchmark.expanding().max()
drawdown_benchmark = (cumulative_benchmark / previous_peaks_benchmark) - 1

plt.figure(figsize=(14, 7))
plt.plot(drawdown_portfolio.index, drawdown_portfolio, label='Dynamic Portfolio Drawdown', color='blue')
plt.plot(drawdown_benchmark.index, drawdown_benchmark, label='S&P 500 Drawdown', color='red', linestyle='--')
plt.title('Drawdown Comparativo: Portfólio Dinâmico vs. S&P 500')
plt.xlabel('Data')
plt.ylabel('Drawdown')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# Calculate and print maximum drawdown for the dynamic portfolio
max_drawdown_portfolio = drawdown_portfolio.min()
print(f"Drawdown Máximo do Portfólio Dinâmico: {max_drawdown_portfolio:.4f}")

import statsmodels.api as sm

# Ensure both series have the same index and are aligned
aligned_returns_alpha_beta = pd.concat([portfolio_returns_dynamic, benchmark_returns], axis=1).dropna()
aligned_portfolio_returns = aligned_returns_alpha_beta.iloc[:, 0]
aligned_benchmark_returns = aligned_returns_alpha_beta.iloc[:, 1]

# Calculate Beta
covariance_pb = aligned_portfolio_returns.cov(aligned_benchmark_returns)
variance_b = aligned_benchmark_returns.var()
beta = covariance_pb / variance_b

# Calculate Alpha
# Annualized returns were calculated previously as dynamic_return_bt and annual_return_benchmark
# The risk-free rate Rf was also previously defined.

alpha_daily = aligned_portfolio_returns.mean() - (Rf/252 + beta * (aligned_benchmark_returns.mean() - Rf/252))
alpha_annualized = alpha_daily * 252

print(f"\nBeta do Portfólio Dinâmico vs. S&P 500: {beta:.4f}")
print(f"Alpha Anualizado do Portfólio Dinâmico vs. S&P 500: {alpha_annualized:.4f}")

plt.figure(figsize=(14, 7))
plt.plot(aligned_portfolio_returns.index, aligned_portfolio_returns, label='Portfólio Dinâmico', alpha=0.7)
plt.plot(aligned_portfolio_returns.index, aligned_benchmark_returns, label='S&P 500', alpha=0.7)
plt.title('Portfólio Dinâmico vs. S&P 500')
plt.xlabel('Data')
plt.ylabel('Retorno')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Análise de Alpha e Beta

*   **Beta**: O Beta mede a sensibilidade do portfólio aos movimentos do mercado (S&P 500 neste caso). Um Beta maior que 1 indica que o portfólio é mais volátil que o mercado, enquanto um Beta menor que 1 sugere menor volatilidade. Um Beta próximo a 1 indica que o portfólio se move em linha com o mercado.

*   **Alpha**: O Alpha mede o retorno excedente do portfólio em comparação com o que seria esperado com base em seu Beta. Um Alpha positivo indica que o portfólio superou seu benchmark ajustado ao risco, enquanto um Alpha negativo sugere o oposto.
"""

portfolio_returns_static = (backtest_returns * weights_opt).sum(axis=1) #CAPM model regression
portfolio_returns_static.dropna()
portfolio_returns_dynamic.dropna()
common_idx = portfolio_returns_dynamic.index.intersection(portfolio_returns_static.index)
portfolio_returns_dynamic = portfolio_returns_dynamic.loc[common_idx]
benchmark_returns = benchmark_returns.loc[common_idx]
portfolio_returns_static = portfolio_returns_static.loc[common_idx]

Rf_daily = Rf / 252
x = (benchmark_returns - Rf_daily).astype(float)
y_dynamic = (portfolio_returns_dynamic - Rf_daily).astype(float)
y_static = (portfolio_returns_static - Rf_daily).astype(float)

model_dynamic_beta = sm.OLS(y_dynamic, sm.add_constant(x)).fit()
beta_dynamic = model_dynamic_beta.params[1]

model_static_beta = sm.OLS(y_static, sm.add_constant(x)).fit()
beta_static = model_static_beta.params[1]

print("\nPortfolio Betas (Backtest CAPM):")
print("Dynamic Portfolio Beta:", round(beta_dynamic,3))
print("Static Portfolio Beta:", round(beta_static,3))

def rolling_beta(y, x, window=60): #rolling beta 60 days
    betas = []
    for i in range(window, len(y)):
        model = sm.OLS(y[i-window:i], sm.add_constant(x[i-window:i])).fit()
        betas.append(model.params[1])
    return pd.Series(betas, index=y.index[window:])

rolling_beta_dynamic = rolling_beta(y_dynamic, x)
rolling_beta_static = rolling_beta(y_static, x)

plt.figure(figsize=(12,5)) #plot comparaison of dynmic portfolio beta to the static one
plt.plot(rolling_beta_dynamic, label="Dynamic Portfolio Beta", color='orange')
plt.plot(rolling_beta_static, label="Static Portfolio Beta", color='blue')
plt.axhline(1.0, color='red', linestyle='--', linewidth=1)
plt.title("Rolling Portfolio Betas (Backtest Period)")
plt.xlabel("Date")
plt.ylabel("Beta")
plt.legend()
plt.grid(alpha=0.3)
plt.show()

import pandas as pd

# Calculate absolute weight changes for all assets during the backtest period
weight_changes_all_assets = dynamic_weights_bt.diff().abs()

# Get the fitted conditional volatility for all assets during the backtest period
# Reindex ms_garch_fitted_vol to align with the backtest period and handle NaNs
volatility_all_assets = ms_garch_fitted_vol.reindex(weight_changes_all_assets.index)

# Initialize a dictionary to store correlations
correlation_results = {}

# Ensure 'assets' variable is available from previous cells
if 'assets' not in locals():
    assets = dynamic_weights_bt.columns.tolist()

# Calculate correlation for each asset
for asset in assets:
    # Create a temporary DataFrame for correlation calculation, dropping NaNs
    temp_df = pd.DataFrame({
        'volatility': volatility_all_assets[asset],
        'weight_change': weight_changes_all_assets[asset]
    }).dropna()

    if not temp_df.empty:
        # Calculate the correlation between absolute weight changes and volatility
        correlation = temp_df['volatility'].corr(temp_df['weight_change'])
        correlation_results[asset] = correlation

# Convert results to a pandas Series for easy sorting
correlation_series = pd.Series(correlation_results)

# Sort the assets by correlation in descending order
ranked_assets = correlation_series.sort_values(ascending=False)

print("Ativos com a maior sensibilidade de ajuste de peso perante a volatilidade (rankeado por correlação):")
display(ranked_assets.head(3))

plt.figure(figsize=(12, 6))
plot_asset = ranked_assets.index[0]
plt.plot(volatility_all_assets[plot_asset], label=f'Volatility ({plot_asset})', color='blue')
plt.plot(weight_changes_all_assets[plot_asset], label=f'Weight Change ({plot_asset})', color='orange')
plt.title(f'Volatility vs. Weight Change for {plot_asset}')
plt.xlabel('Date')
plt.ylabel('Value')
plt.legend()
plt.grid(True)
plt.show()

asset_to_plot = 'MU'

# Obter a probabilidade de regime de alta volatilidade para o ativo selecionado
prob_high_vol = regime_prob_bt[asset_to_plot]

# Obter as mudanças absolutas nos pesos para o ativo selecionado
# 'weight_diff' já contém a diferença diária dos pesos, precisamos do valor absoluto para as 'trocas'
weight_changes_asset = dynamic_weights_bt[asset_to_plot].diff().abs()

# Alinhar os índices para garantir que estamos comparando as datas corretas
common_index = prob_high_vol.index.intersection(weight_changes_asset.index)
prob_high_vol_aligned = prob_high_vol.loc[common_index]
weight_changes_asset_aligned = weight_changes_asset.loc[common_index]

plt.figure(figsize=(14, 7))

# Plotar a probabilidade de regime de alta volatilidade
plt.plot(prob_high_vol_aligned.index, prob_high_vol_aligned, label=f'Probabilidade de Regime de Alta Volatilidade ({asset_to_plot})', color='red', alpha=0.7)
plt.title(f'Probabilidade de Regime de Alta Volatilidade vs. Mudanças de Peso para {asset_to_plot}')
plt.xlabel('Data')
plt.ylabel('Probabilidade / Mudança de Peso Absoluta')
plt.grid(True, linestyle='--', alpha=0.7)

# Criar um segundo eixo Y para as mudanças de peso
ax2 = plt.twinx()
ax2.plot(weight_changes_asset_aligned.index, weight_changes_asset_aligned, label=f'Mudança Absoluta de Peso ({asset_to_plot})', color='blue', linestyle='--')
ax2.set_ylabel('Mudança Absoluta de Peso', color='blue')

plt.legend(loc='upper left')
ax2.legend(loc='upper right')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Os três ativos com a maior correlação (obtidos da execução anterior)
top_3_assets = ranked_assets.head(3).index.tolist()

plt.figure(figsize=(15, 5))

for i, asset in enumerate(top_3_assets):
    plt.subplot(1, 3, i + 1)
    sns.histplot(weight_changes_all_assets[asset].dropna(), bins=30, kde=True)
    plt.title(f'Distribuição de Mudança de Peso para {asset}')
    plt.xlabel('Mudança Absoluta de Peso')
    plt.ylabel('Frequência')

plt.tight_layout()
plt.show()

import subprocess
packages = ['yfinance', 'arch', 'pykalman', 'statsmodels', 'xgboost', 'scipy', 'matplotlib', 'pandas', 'numpy', 'scikit-learn']
for pkg in packages:
    subprocess.run(['pip', 'install', pkg, '-q'], check=False)
print('Dependencias instaladas correctamente.')

import statsmodels.api as sm
import matplotlib.pyplot as plt # Importar matplotlib
import numpy as np # Importar numpy

# Define 'retornos' using 'combined_returns' from previous cells
# Note: 'JPM' and 'GS' are not available in 'combined_returns' and will cause a KeyError if used.
retornos = combined_returns

# Preparar datos
y = retornos['AMZN'].values
X_simple = retornos['^GSPC'].values
X_multi = retornos[['^GSPC']].values

# Regresión simple: AAPL ~ S&P500
X1 = sm.add_constant(X_simple)
modelo_simple = sm.OLS(y, X1).fit()

# Regresión múltiple: AAPL ~ S&P500 + JPM + GS
X2 = sm.add_constant(X_multi)
modelo_multi = sm.OLS(y, X2).fit()

# Visualización
fig, axes = plt.subplots(1, 2, figsize=(14, 6))
fig.suptitle('Modelo 1: Regresión Lineal y Múltiple', fontsize=14, color='white', fontweight='bold')

# Scatter con línea de regresión
ax = axes[0]
ax.scatter(X_simple, y, alpha=0.3, color='white', s=8, label='Observaciones')
x_line = np.linspace(X_simple.min(), X_simple.max(), 100)
y_line = modelo_simple.params[0] + modelo_simple.params[1] * x_line
ax.plot(x_line, y_line, color='#00d4ff', linewidth=2, label=f'β={modelo_simple.params[1]:.3f}, α={modelo_simple.params[0]:.5f}')
residuals_x = X_simple[:50]
residuals_y_obs = y[:50]
residuals_y_pred = modelo_simple.params[0] + modelo_simple.params[1] * residuals_x
for xi, yi_obs, yi_pred in zip(residuals_x, residuals_y_obs, residuals_y_pred):
    ax.plot([xi, xi], [yi_obs, yi_pred], color='red', alpha=0.4, linewidth=0.7)
ax.set_xlabel('Retorno S&P 500 (Factor de Mercado)')
ax.set_ylabel('Retorno Amazon')
ax.set_title(f'Regresión Simple\nR² = {modelo_simple.rsquared:.3f}', color='white')
ax.legend(fontsize=8)
ax.grid(True, alpha=0.3)

# Coeficientes del modelo múltiple
ax2 = axes[1]
coefs = modelo_multi.params[1:]
conf = modelo_multi.conf_int()[1:]

nombres = ['β_Mercado\n(S&P500)', 'β_Banca\n(JPM)', 'β_Banca\nInversión (GS)']
colores = ['#00d4ff', '#ffd700', '#00ff88']

bars = ax2.bar(nombres, coefs, color=colores, alpha=0.8, edgecolor='white', linewidth=0.5)

for bar, ci_low, ci_high in zip(bars, conf[:, 0], conf[:, 1]):
    centro = bar.get_height()
    lower = min(ci_low, ci_high)
    upper = max(ci_low, ci_high)

    err_low = abs(centro - lower)
    err_high = abs(upper - centro)

    ax2.errorbar(
        bar.get_x() + bar.get_width()/2,
        centro,
        yerr=[[err_low], [err_high]],
        fmt='none',
        color='white',
        capsize=5
    )

ax2.axhline(y=0, color='white', linewidth=0.8, linestyle='--', alpha=0.5)
ax2.set_title(f'Regresión Múltiple - Coeficientes Beta\nR² = {modelo_multi.rsquared:.3f}', color='white')
ax2.set_ylabel('Coeficiente Beta')
ax2.grid(True, alpha=0.3, axis='y')

plt.tight_layout()
plt.savefig('modelo1_regresion.png', dpi=150, bbox_inches='tight', facecolor='#050a14')
plt.show()

print('\n=== RESUMEN REGRESIÓN SIMPLE ===')
print(f'Alpha (α):  {modelo_simple.params[0]:.6f}  (p-valor: {modelo_simple.pvalues[0]:.4f})')
print(f'Beta  (β):  {modelo_simple.params[1]:.4f}  (p-valor: {modelo_simple.pvalues[1]:.4f})')
print(f'R²:         {modelo_simple.rsquared:.4f}')
print(f'\n=== RESUMEN REGRESIÓN MÚLTIPLE ===')
print(modelo_multi.summary().tables[1])

fig.text(
    0.01, 0.01,
    "Elaboração: Benjamim.J",
    fontsize=10, color="blue",
    horizontalalignment="left",
    verticalalignment="bottom",
    transform=fig.transFigure
)

assets = ['AMZN', 'MU', 'NVDA', 'AAPL','AMD','ORCL','XOM']
benchmark = '^GSPC'

#  ARIMA y GARCH
from statsmodels.tsa.arima.model import ARIMA
from arch import arch_model

# Usar retornos del S&P 500 (en %)
ret_sp500 = retornos['^GSPC'] * 1000

# Ajustar ARIMA(1,0,1)
arima = ARIMA(ret_sp500, order=(1, 0, 1)).fit()

# Ajustar GARCH(1,1)
garch = arch_model(ret_sp500, vol='Garch', p=1, q=1, dist='normal').fit(disp='off')
vol_condicional = garch.conditional_volatility

# Visualización
fig, axes = plt.subplots(3, 1, figsize=(14, 12))
fig.suptitle(' ARIMA x GARCH — S&P 500', fontsize=14, color='black', fontweight='bold')

# Serie de retornos
ax1 = axes[0]
ax1.plot(ret_sp500.index, ret_sp500.values, color='#00d4ff', linewidth=0.7, alpha=0.9)
ax1.axhline(0, color='white', linewidth=0.5, linestyle='--', alpha=0.5)
ax1.set_title('Retornos Diarios S&P 500 (%)', color='white')
ax1.set_ylabel('Retorno (%)')
ax1.grid(True, alpha=0.3)
# Marcar crisis
ax1.axvspan(pd.Timestamp('2020-02-01'), pd.Timestamp('2020-05-01'), alpha=0.2, color='red', label='COVID-19 (2020)')
ax1.axvspan(pd.Timestamp('2022-01-01'), pd.Timestamp('2022-12-01'), alpha=0.15, color='orange', label='Inflación (2022)')
ax1.legend(fontsize=8)

# Volatilidad condicional GARCH
ax2 = axes[1]
ax2.fill_between(vol_condicional.index, vol_condicional.values, alpha=0.7, color='#ffd700')
ax2.plot(vol_condicional.index, vol_condicional.values, color='#ffd700', linewidth=0.8)
ax2.set_title(f'Volatilidad Condicional GARCH(1,1) — ω={garch.params["omega"]:.4f}, α={garch.params["alpha[1]"]:.4f}, β={garch.params["beta[1]"]:.4f}', color='white')
ax2.set_ylabel('σ_t (%)')
ax2.grid(True, alpha=0.3)
ax2.axvspan(pd.Timestamp('2020-02-01'), pd.Timestamp('2020-05-01'), alpha=0.2, color='red')

# ACF de retornos al cuadrado (evidencia de ARCH)
from statsmodels.graphics.tsaplots import plot_acf
plot_acf(ret_sp500**2, lags=30, ax=axes[2], color='#00d4ff', alpha=0.05)
axes[2].set_title('ACF de Retornos² — Evidencia de Agrupación de Volatilidad', color='white')
axes[2].set_xlabel('Rezago')
axes[2].set_ylabel('Autocorrelación')

plt.tight_layout()
plt.savefig('modelo2_arima_garch.png', dpi=150, bbox_inches='tight', facecolor='#050a14')
plt.show()

print('--PARÁMETROS GARCH(1,1)--')
print(garch.summary().tables[1])
print(f'\nPersistencia (α+β): {garch.params["alpha[1]"] + garch.params["beta[1]"]:.4f} (debe ser < 1)')

fig.text(
    0.01, -0.02,
     "Elaboração: Benjamim.J",
    fontsize=10, color="blue",
    horizontalalignment="left",
    verticalalignment="top",
    transform=fig.transFigure
)

import warnings
warnings.filterwarnings('ignore')

# MODELO 3: FILTRO DE KALMAN — Beta Dinámica asset vs S&P500
# !pip install pykalman -q # Já deve estar instalado ou é executado no início do notebook
from pykalman import KalmanFilter

# Certifique-se de que `retornos` e `benchmark_returns_aligned` estão disponíveis
# `retornos` é na verdade `combined_returns` de uma célula anterior, que inclui S&P500
# `benchmark_returns_aligned` é a série de retornos do S&P 500

# Preparar dados para beta dinâmica: usar `retornos` que contém todos os ativos e S&P500
x_sp500 = retornos['^GSPC'].values

# Dicionários para armazenar os resultados de beta e alpha para cada ativo
all_betas = {}
all_alphas = {}

# Loop sobre cada ativo no DataFrame `retornos` (excluindo o benchmark S&P500)
for asset in [col for col in retornos.columns if col != '^GSPC']:
    print(f"\n--- Calculando Beta Dinâmica para {asset} ---")
    y_asset = retornos[asset].values

    # Configurar Filtro de Kalman para estimar beta dinâmica
    # Estado: [alpha, beta] — ambos varíam en el tiempo
    n = len(y_asset)
    delta = 1e-5  # factor de suavizado

    # Implementação manual do Filtro de Kalman para beta dinámica
    betas = np.zeros(n)
    alphas = np.zeros(n)
    P = np.eye(2)  # covarianza del estado
    Q = delta / (1 - delta) * np.eye(2)  # ruido del proceso
    R = 1.0  # varianza del ruido de observación
    theta = np.array([0.0, 1.0])  # estado inicial: alpha=0, beta=1

    for t in range(n):
        # Vector de observación
        F = np.array([1.0, x_sp500[t]])

        # Predição
        y_pred = F @ theta
        S = F @ P @ F.T + R

        # Ganancia de Kalman
        K = P @ F.T / S

        # Actualização
        theta = theta + K * (y_asset[t] - y_pred)
        P = (np.eye(2) - np.outer(K, F)) @ P + Q

        alphas[t] = theta[0]
        betas[t] = theta[1]

    # Armazenar resultados
    all_betas[asset] = betas
    all_alphas[asset] = alphas

    # Calcular métricas
    beta_estatica = np.cov(y_asset, x_sp500)[0,1] / np.var(x_sp500)
    mean_dynamic_beta = betas.mean()
    # Período COVID para cálculo de beta dinâmica durante o evento
    fechas = retornos.index
    covid_start = pd.Timestamp('2020-02-01')
    covid_end = pd.Timestamp('2020-05-01')
    covid_betas = betas[(fechas >= covid_start) & (fechas <= covid_end)]
    beta_during_covid = covid_betas.mean() if len(covid_betas) > 0 else np.nan

    print(f'Beta estática {asset}: {beta_estatica:.4f}')
    print(f'Beta dinâmica promedio {asset}: {mean_dynamic_beta:.4f}')
    print(f'Beta dinâmica durante COVID {asset} (feb-may 2020): {beta_during_covid:.4f}')

# Visualização para os ativos solicitados
print("\n--- Gerando gráficos para JPM, MU e REMX ---")
assets_to_plot = ['JPM', 'MU', 'REMX']

for asset in assets_to_plot:
    fig, axes = plt.subplots(2, 1, figsize=(14, 10))
    fig.suptitle(f'Modelo 3: Filtro de Kalman — Beta Dinâmica {asset} vs S&P 500', fontsize=14, color='white', fontweight='bold')

    # Beta dinámica
    ax1 = axes[0]
    fechas = retornos.index
    ax1.plot(fechas, all_betas[asset], color='#00d4ff', linewidth=1.2, label=f'Beta Dinâmica (Kalman) {asset}')

    # Recalcular beta estática para o plot
    y_current_asset = retornos[asset].values
    beta_estatica_plot = np.cov(y_current_asset, x_sp500)[0,1] / np.var(x_sp500)

    ax1.axhline(beta_estatica_plot, color='#ffd700', linewidth=1.5, linestyle='--', label=f'Beta Estática = {beta_estatica_plot:.3f}')
    ax1.axhline(1.0, color='white', linewidth=0.8, linestyle=':', alpha=0.5, label='Beta = 1 (mercado)')
    ax1.axvspan(covid_start, covid_end, alpha=0.2, color='red', label='COVID-19')
    ax1.set_title(f'Beta Dinâmica: {asset} vs S&P 500', color='white')
    ax1.set_ylabel('Beta')
    ax1.legend(fontsize=9)
    ax1.grid(True, alpha=0.3)

    # Alpha dinámico
    ax2 = axes[1]
    ax2.plot(fechas, all_alphas[asset] * 252, color='#00ff88', linewidth=1.0, label=f'Alpha Anualizado (Kalman) {asset}')
    ax2.axhline(0, color='white', linewidth=0.8, linestyle='--', alpha=0.5)
    ax2.fill_between(fechas, all_alphas[asset] * 252, 0, where=(all_alphas[asset] * 252 > 0), alpha=0.3, color='#00ff88', label='Alpha positivo')
    ax2.fill_between(fechas, all_alphas[asset] * 252, 0, where=(all_alphas[asset] * 252 < 0), alpha=0.3, color='red', label='Alpha negativo')
    ax2.set_title(f'Alpha Dinâmico Anualizado: {asset}', color='white')
    ax2.set_ylabel('Alpha Anualizado')
    ax2.legend(fontsize=9)
    ax2.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(f'modelo3_kalman_{asset}.png', dpi=150, bbox_inches='tight', facecolor='#050a14')
    plt.show()

print("\n--- Calculando Alpha Acumulado para JPM, MU e REMX durante a COVID ---")

# Ativos para os quais queremos calcular o Alpha acumulado
assets_to_analyze = ['JPM', 'MU', 'REMX']

# Período COVID
covid_start = pd.Timestamp('2020-02-01')
covid_end = pd.Timestamp('2020-05-01')

for asset in assets_to_analyze:
    if asset in all_alphas:
        # Obter a série de alphas para o ativo
        alpha_series = pd.Series(all_alphas[asset], index=retornos.index)

        # Filtrar alphas para o período COVID
        covid_alpha_series = alpha_series[(alpha_series.index >= covid_start) & (alpha_series.index <= covid_end)]

        if not covid_alpha_series.empty:
            # Calcular o alpha acumulado (anualizado para fins de visualização se desejar, mas para acumulado, usamos o diário)
            # Multiplicamos por 252 para anualizar, se for o caso, mas para "acumulado" é a soma dos retornos diários
            cumulative_alpha = (1 + covid_alpha_series).cumprod() - 1

            print(f"Alpha Acumulado para {asset} durante a COVID (2020-02 a 2020-05): {cumulative_alpha.iloc[-1]:.4f}")

            # Plotar o Alpha acumulado durante a COVID
            plt.figure(figsize=(12, 6))
            plt.plot(cumulative_alpha.index, cumulative_alpha, label=f'Alpha Acumulado {asset}')
            plt.title(f'Alpha Acumulado para {asset} durante a COVID-19')
            plt.xlabel('Data')
            plt.ylabel('Alpha Acumulado')
            plt.grid(True, linestyle='--', alpha=0.7)
            plt.legend()
            plt.tight_layout()
            plt.show()
        else:
            print(f"Nenhum dado de Alpha para {asset} encontrado durante o período da COVID.")
    else:
        print(f"Alpha para {asset} não encontrado nos resultados.")

num_simulations = 10000  # Número de simulações de Monte Carlo
num_days = 252  # Número de dias úteis em um ano para o cálculo anualizado
confidence_level = 0.95  # Nível de confiança para o VaR

# Alinhar os índices dos retornos do portfólio dinâmico com o retorno do benchmark.
# Já temos `portfolio_returns_dynamic` e `benchmark_returns` alinhados na célula `639ced8e`,
# mas para garantir a consistência para o cálculo de média e desvio padrão do portfólio completo,
# vamos usar os `returns_aligned` que incluem todos os ativos.

# Calculando o retorno médio e desvio padrão histórico do portfólio (usando pesos estáticos para simplificar a média histórica do portfólio)
# Para o VaR de Monte Carlo, geralmente precisamos da média e do desvio padrão do portfólio.
# Podemos usar os pesos ótimos fixos (`weights_opt`) calculados anteriormente para uma estimativa do portfólio.

# O `returns_aligned` já foi definido em células anteriores e contém os retornos de todos os ativos.
# Calcula a média e a matriz de covariância dos retornos dos ativos.
mean_returns_assets = returns_aligned.mean()
cov_matrix_assets = returns_aligned.cov()

# Assume-se que `weights_opt` (pesos ótimos fixos) está disponível de células anteriores
# Se `weights_opt` não estiver definido, você precisará defini-lo ou carregar de uma fonte.
# Exemplo para garantir `weights_opt`:
# weights_opt = pd.Series([1/len(assets) for _ in assets], index=assets) # Portfólio equiponderado de exemplo

# Calculando o retorno e volatilidade do portfólio usando os pesos ótimos fixos
portfolio_mean_return = (weights_opt * mean_returns_assets).sum()
portfolio_std_dev = np.sqrt(weights_opt.T @ cov_matrix_assets @ weights_opt)

# Simulação de Monte Carlo
# Gerar retornos aleatórios para o portfólio
simulated_returns = np.random.normal(portfolio_mean_return, portfolio_std_dev, (num_simulations, num_days))

# Calcular o valor final do portfólio para cada simulação (partindo de 1 unidade de capital)
initial_capital = 1.0
simulated_portfolio_values = initial_capital * (1 + simulated_returns).prod(axis=1)

# Calcular o VaR
var_monte_carlo = np.percentile(simulated_portfolio_values, (1 - confidence_level) * 100)

print(f"VaR do portfólio (Monte Carlo, {confidence_level*100:.0f}% de confiança) em {num_days} dias: {var_monte_carlo:.4f}")


# Visualizar a distribuição dos valores finais do portfólio simulado
plt.figure(figsize=(12, 6))
sns.histplot(simulated_portfolio_values, bins=50, kde=True, color='skyblue')
plt.axvline(var_monte_carlo, color='red', linestyle='--', label=f'VaR ({confidence_level*100:.0f}%) = {var_monte_carlo:.4f}')
plt.title('Distribuição dos Valores Finais do Portfólio (Simulação Monte Carlo)')
plt.xlabel('Valor Final do Portfólio')
plt.ylabel('Frequência')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

"""### algumas "Gregas" e hedge no portifolio

**Delta (Δ)**: Mede a sensibilidade do preço da opção a uma mudança de 1 unidade no preço do ativo subjacente. Um Delta de 0.04, por exemplo, significa que para cada aumento de $1 no preço do IBOV, o preço da opção aumentaria $0.04.

 **Gamma (Γ)**: Mede a taxa de variação do Delta em relação a uma mudança de 1 unidade no preço do ativo subjacente. Um Gamma de 0.0075 indica que o Delta da opção mudará em 0.0075 para cada $1 de movimento no preço do IBOV. Gamma é importante para entender como o Delta se comportará em diferentes cenários de mercado.

**Vega (ν)**: Mede a sensibilidade do preço da opção a uma mudança de 1% na volatilidade implícita do ativo subjacente. Um Vega de 0.0006 significa que, se a volatilidade do IBOV aumentar em 1%, o preço da opção aumentaria $0.0006.
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import yfinance as yf
from scipy.stats import norm

def black_scholes_call(S, K, T, r, sigma):
    """
    Calcula o preço de uma opção de compra (Call) usando o modelo Black-Scholes.

    Parâmetros:
    S (float): Preço atual do ativo subjacente
    K (float): Preço de exercício da opção
    T (float): Tempo até a expiração (em anos)
    r (float): Taxa de juros livre de risco anual (em decimal)
    sigma (float): Volatilidade anual do ativo subjacente (em decimal)

    Retorna:
    float: Preço da opção de compra
    """
    d1 = (np.log(S / K) + (r + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)

    call_price = S * norm.cdf(d1) - K * np.exp(-r * T) * norm.cdf(d2)
    return call_price

def black_scholes_put(S, K, T, r, sigma):
    """
    Calcula o preço de uma opção de venda (Put) usando o modelo Black-Scholes.

    Parâmetros:
    S (float): Preço atual do ativo subjacente
    K (float): Preço de exercício da opção
    T (float): Tempo até a expiração (em anos)
    r (float): Taxa de juros livre de risco anual (em decimal)
    sigma (float): Volatilidade anual do ativo subjacente (em decimal)

    Retorna:
    float: Preço da opção de venda
    """
    d1 = (np.log(S / K) + (r + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)

    put_price = K * np.exp(-r * T) * norm.cdf(-d2) - S * norm.cdf(-d1)
    return put_price

# Parâmetros da opção do IBOV
option_ticker = 'IBOV260819C00035000' # Exemplo de ticker no formato esperado (IBOV + YYMMDD + Tipo + Strike * 1000)


expiration_date_str = option_ticker[4:10] # '260819' (ajustado para o novo formato)
expiration_year = 2000 + int(expiration_date_str[0:2]) # 2026
expiration_month = int(expiration_date_str[2:4]) # 08
expiration_day = int(expiration_date_str[4:6]) # 19
expiration_date = pd.Timestamp(year=expiration_year, month=expiration_month, day=expiration_day)

K = float(option_ticker[11:]) / 1000 # '00035000' -> 35.000 -> 35 (ajustado para o novo formato)
option_type = option_ticker[10:11] # 'C' (ajustado para o novo formato)

print(f"Ticker da Opção: {option_ticker}")
print(f"Tipo da Opção: {option_type}")
print(f"Preço de Exercício (K): {K}")
print(f"Data de Expiração: {expiration_date.strftime('%Y-%m-%d')}")

vix_data = yf.download('^BVSP', start='2020-01-01', end=pd.Timestamp.today().strftime('%Y-%m-%d'))['Close'] # Usando ^BVSP para IBOV

#Preço à vista (S) - último preço do IBOV
S = vix_data.iloc[-1].item() # Extrair o valor

# Calcular o tempo até a expiração (T) em anos e Considera dias úteis para cálculo de T mais preciso, mas aqui usamos a diferença de dias totais / 365
delta_t = (expiration_date - pd.Timestamp.today()).days
if delta_t < 0:
    T = 0 # Opção já expirada ou no limite
    print("A opção já expirou. Calculando com T=0.")
else:
    T = delta_t / 365.25 # Usar 365.25 para considerar anos bissextos

#Taxa livre de risco (r) - usando 'Rf' anual)
r = Rf

#Volatilidade (sigma) - volatilidade histórica anualizada do ibov + Usar uma janela de, por exemplo, 252 dias úteis (1 ano) de retornos do ibovespa
vix_returns = np.log(vix_data / vix_data.shift(1)).dropna()
sigma = vix_returns.std().item() * np.sqrt(252)

print(f"\nPreço Atual do IBOV (S): {S:.2f}")
print(f"Tempo até a Expiração (T) em anos: {T:.4f}")
print(f"Taxa Livre de Risco Anual (r): {r:.4f}")
print(f"Volatilidade Anual do IBOV (sigma): {sigma:.4f}")

#preço da opção usando o modelo Black-Scholes
if option_type == 'C':
    option_price = black_scholes_call(S, K, T, r, sigma)
    print(f"\nPreço da Opção de Compra (Call) Black-Scholes para {option_ticker}: {option_price:.2f}")
elif option_type == 'P':
    option_price = black_scholes_put(S, K, T, r, sigma)
    print(f"\nPreço da Opção de Venda (Put) Black-Scholes para {option_ticker}: {option_price:.2f}")
else:
    print("Tipo de opção não reconhecido. Suporta apenas 'C' (Call) e 'P' (Put).")


#Plotar o histórico do ibov
plt.figure(figsize=(12, 6))
plt.plot(vix_data.index, vix_data.values, label='Índice IBOV Histórico', color='blue')
                                                                                                     # Delta (Δ) : Mede a sensibilidade do preço da opção a uma mudança de 1 unidade no preço do ativo subjacente. Um Delta de 0,04, por exemplo, significa que para cada aumento de $1 no preço do IBOV, o preço da opção aumentaria $ 0,04.

                                                                                                     #Gamma (Γ): Mede a taxa de variação do Delta em relação a uma mudança de 1 unidade no preço do ativo subjacente. Um Gamma de 0.0075 indica que o Delta da opção mudará em 0.0075 para cada $1 de movimento no preço do IBOV.
                                                                                                      # Gamma é importante para entender como o Delta se comportará em diferentes cenários de mercado.

                                                                                                      #Vega (ν) : Mede a sensibilidade do preço da opção a uma mudança de 1% na volatilidade implícita do ativo subjacente. Um Vega de 0,0006 significa que, se a volatilidade do IBOV aumentar em 1%, o preço da opção aumentaria $ 0,0006.
plt.axhline(S, color='red', linestyle='--', label=f'IBOV Spot Price: {S:.2f}')
plt.axhline(K, color='green', linestyle=':', label=f'Strike Price (K): {K:.2f}')
plt.title('Histórico do Índice IBOV com Preços Spot e Strike')
plt.xlabel('Data')
plt.ylabel('Valor do IBOV')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()


def black_scholes_delta(S, K, T, r, sigma, option_type):
    """
    Calcula o Delta de uma opção usando o modelo Black-Scholes.
    """
    d1 = (np.log(S / K) + (r + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))

    if option_type == 'C':
        return norm.cdf(d1)
    elif option_type == 'P':
        return norm.cdf(d1) - 1
    else:
        return None


     #'GAMA'

def black_scholes_gamma(S, K, T, r, sigma):
    """
    Calcula o Gamma de uma opção usando o modelo Black-Scholes.
    """
    d1 = (np.log(S / K) + (r + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))
    gamma = norm.pdf(d1) / (S * sigma * np.sqrt(T))
    return gamma

#'VegA'
def black_scholes_vega(S, K, T, r, sigma):
    """
    Calcula o Vega de uma opção usando o modelo Black-Scholes.
    """
    d1 = (np.log(S / K) + (r + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))
    vega = S * norm.pdf(d1) * np.sqrt(T)
    return vega

#  "gregas"

def black_scholes_theta(S, K, T, r, sigma):
    """
    Calcula o Theta de uma opção usando o modelo Black-Scholes.
    """
    d1 = (np.log(S / K) + (r + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)
    theta = (-S * norm.pdf(d1) * sigma) / (2 * np.sqrt(T)) - r * K * np.exp(-r * T) * norm.cdf(d2)
    return theta
    # Theta geralmente é anualizado, mas pode ser expresso por dia (dividindo por 365)
    return theta / 365

def black_scholes_rho(S,K,T,r,sigma):
    """
    Calcula o Rho de uma opção usando o modelo Black-Scholes.
    """
    d1 = (np.log(S / K) + (r + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)
    rho = K * T * np.exp(-r * T) * norm.cdf(d2)
    return rho / 100
    # Rho é sensibilidade a 1% de mudança na taxa de juros
    return rho

# Calculate Greeks after option_price is defined
delta = black_scholes_delta(S, K, T, r, sigma, option_type)
gamma = black_scholes_gamma(S, K, T, r, sigma)
vega = black_scholes_vega(S, K, T, r, sigma)
theta = black_scholes_theta(S, K, T, r, sigma)
rho = black_scholes_rho(S, K, T, r, sigma)

print('---PREÇO DAS OPÇÕES--- ')
print(f"\nPreço da Opção ({option_type}): {option_price:.2f}")
print(f"Delta da Opção ({option_type}): {delta:.4f}")
print(f"Gamma da Opção: {gamma:.4f}")
print(f"Vega da Opção: {vega:.4f}")
print(f"Theta da Opção ({option_type}) por dia: {theta:.4f}")
print(f"Rho da Opção ({option_type}): {rho:.4f}")

print('------VALOR,STRIKE, VOL (IBOV)------- ')

print(f"Strike Price (K): {K:.2f}")
print(f"Data de Expiração: {expiration_date.strftime('%Y-%m-%d')}")
print(f"Preço Atual do IBOV (S): {S:.2f}")
print(f"Tempo até a Expiração (T) em anos: {T:.4f}")
print(f"Taxa Livre de Risco Anual (r): {r:.4f}")
print(f"Volatilidade Anual do IBOV (sigma): {sigma:.4f}")

# Definir parâmetros para a simulação OOS (Out-of-Sample)
num_simulations = 1000  # Número de cenários
oos_days = 252

       #última data do período de backtest para iniciar a simulação OOS
start_date_oos = portfolio_returns_dynamic.index[-1]
oos_dates = pd.date_range(start=start_date_oos + pd.Timedelta(days=1), periods=oos_days)

#pesos dinâmicos finais do backtest
weights_current = weights_shifted.iloc[-1] # Usar os últimos pesos do período de backtest

 # retornos diários médios e matriz de covariância diária de todos os ativos
mean_daily_returns = daily_avg_returns
cov_daily_matrix = cov_matrix_assets

    # Inicializar DataFrame para armazenar todos os caminhos cumulativos simulados
simulated_cumulative_paths = pd.DataFrame(index=oos_dates)

         #simulação de Monte Carlo
for s in range(num_simulations):

    simulated_returns_oos_array = np.random.multivariate_normal(
        mean_daily_returns.values,
        cov_daily_matrix.values,
        oos_days
    )
    simulated_returns_oos_df = pd.DataFrame(simulated_returns_oos_array, index=oos_dates, columns=mean_daily_returns.index)

    # os retornos diários do portfólio simulado usando os pesos atuais
    simulated_portfolio_daily_returns = (simulated_returns_oos_df * weights_current).sum(axis=1)

    # o caminho cumulativo do portfólio simulado e O valor inicial é o valor cumulativo final do backtest
    last_cumulative_value_backtest = cumulative_portfolio.iloc[-1] if not cumulative_portfolio.empty else 1.0
    simulated_cumulative_paths[f'Path_{s}'] = last_cumulative_value_backtest * (1 + simulated_portfolio_daily_returns).cumprod()

# Converter para todos os dados são numéricos
simulated_cumulative_paths = simulated_cumulative_paths.astype(float)

# Plota resultados
plt.figure(figsize=(16, 8))

# Plotar o caminho cumulativo histórico (backtest)
plt.plot(cumulative_portfolio.index, cumulative_portfolio, label='Portfólio Dinâmico (Histórico)', color='blue', linewidth=2)

# Plotar alguns caminhos simulados para visualização
num_sample_paths = min(20, num_simulations) # Plotar no máximo 20 caminhos para não sobrecarregar
for i in range(num_sample_paths):
    plt.plot(simulated_cumulative_paths.index, simulated_cumulative_paths[f'Path_{i}'], color='gray', alpha=0.3, linewidth=0.8)

# Plotar o caminho médio dos cenários simulados
mean_simulated_path = simulated_cumulative_paths.mean(axis=1)
plt.plot(mean_simulated_path.index, mean_simulated_path, label='Caminho Médio Simulado (OOS)', color='red', linestyle='--', linewidth=2)

# Plotar os intervalos de confiança (ex: 5º e 95º percentis)
lower_bound = simulated_cumulative_paths.quantile(0.05, axis=1)
upper_bound = simulated_cumulative_paths.quantile(0.95, axis=1)
plt.fill_between(oos_dates, lower_bound, upper_bound, color='red', alpha=0.1, label='Intervalo de Confiança (5%-95%)')


plt.title('CPCV-OOS: Distribuição do Caminho do Valor Cumulativo do Portfólio (OOS)')
plt.xlabel('Data')
plt.ylabel('Valor Cumulativo do Portfólio (Crescimento de $1)')
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend()
plt.tight_layout()
plt.show()


final_portfolio_values_series = pd.Series(simulated_portfolio_values)
descriptive_stats = final_portfolio_values_series.describe()
print("Estatísticas Descritivas dos Valores Finais do Portfólio Simulado:")
display(descriptive_stats)

plt.figure(figsize=(12, 6))
sns.histplot(simulated_portfolio_values, bins=50, kde=True, color='skyblue')
plt.title('Distribuição de Frequências dos Valores Finais do Portfólio Simulado')
plt.xlabel('Valor Final do Portfólio')
plt.ylabel('Frequência')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

from statsmodels.tsa.stattools import coint, adfuller

#  AAPL y MSFT
p_aapl = prices['BTC-USD'].dropna()
p_msft = prices['AMZN'].dropna()

# Alinhar os índices dos preços após remover NaNs para garantir que ambos tenham as mesmas datas
common_index = p_aapl.index.intersection(p_msft.index)
p_aapl = p_aapl.loc[common_index]
p_msft = p_msft.loc[common_index]

# Test de cointegración de Engle-Granger
score, pvalue, _ = coint(p_aapl, p_msft)
print(f'Test de Cointegración Engle-Granger:')
print(f'  Estadístico: {score:.4f}')
print(f'  p-valor:     {pvalue:.4f}')
print(f'  Conclusión:  {"Cointegradas (rechazamos H0)" if pvalue < 0.05 else "No cointegradas"}')

# Calcular o spread
beta_coint = np.polyfit(p_msft, p_aapl, 1)[0]
spread = p_aapl - beta_coint * p_msft
spread_norm = (spread - spread.mean()) / spread.std()  # Z-score

# Senario trading
umbral_entrada = 2.0
umbral_salida = 0.5
senales = pd.Series(0, index=spread_norm.index)
senales[spread_norm > umbral_entrada] = -1   # Vender spread
senales[spread_norm < -umbral_entrada] = 1   # Comprar spread

# Visualiza
fig, axes = plt.subplots(3, 1, figsize=(14, 12))
fig.suptitle('Modelo 4: Cointegración y Pairs Trading — BTC-USD vs AMZN', fontsize=14, color='white', fontweight='bold')

# Precos normalizados
ax1 = axes[0]
p_aapl_norm = p_aapl / p_aapl.iloc[0] * 100
p_msft_norm = p_msft / p_msft.iloc[0] * 100
ax1.plot(p_aapl_norm.index, p_aapl_norm.values, color='#00d4ff', linewidth=1.2, label='BTC-USD (base 100)')
ax1.plot(p_msft_norm.index, p_msft_norm.values, color='#ffd700', linewidth=1.2, label='AMZN (base 100)')
ax1.set_title('Preços Normalizados (Base 100)', color='white')
ax1.set_ylabel('Preço (base 100)')
ax1.legend()
ax1.grid(True, alpha=0.3)

# Spread Z-score
ax2 = axes[1]
ax2.plot(spread_norm.index, spread_norm.values, color='white', linewidth=0.8, alpha=0.9)
ax2.axhline(0, color='white', linewidth=0.8, linestyle='--', alpha=0.5)
ax2.axhline(umbral_entrada, color='red', linewidth=1.5, linestyle='--', label=f'+{umbral_entrada}σ (Vender spread)')
ax2.axhline(-umbral_entrada, color='#00ff88', linewidth=1.5, linestyle='--', label=f'-{umbral_entrada}σ (Comprar spread)')
ax2.fill_between(spread_norm.index, spread_norm.values, umbral_entrada, where=(spread_norm > umbral_entrada), alpha=0.4, color='red')
ax2.fill_between(spread_norm.index, spread_norm.values, -umbral_entrada, where=(spread_norm < -umbral_entrada), alpha=0.4, color='#00ff88')
ax2.set_title(f'Spread Z-score — p-valor cointegración: {pvalue:.4f}', color='white')
ax2.set_ylabel('Z-score do Spread')
ax2.legend(fontsize=9)
ax2.grid(True, alpha=0.3)

# Senario de trading
ax3 = axes[2]
compras = senales[senales == 1].index
ventas = senales[senales == -1].index
ax3.plot(spread_norm.index, spread_norm.values, color='#888888', linewidth=0.6, alpha=0.7)
ax3.scatter(compras, spread_norm[compras], color='#00ff88', s=30, zorder=5, label=f'Comprar ({len(compras)} señales)', marker='^')
ax3.scatter(ventas, spread_norm[ventas], color='red', s=30, zorder=5, label=f'Vender ({len(ventas)} señales)', marker='v')
ax3.axhline(umbral_entrada, color='red', linewidth=1, linestyle='--', alpha=0.5)
ax3.axhline(-umbral_entrada, color='#00ff88', linewidth=1, linestyle='--', alpha=0.5)
ax3.set_title('Sinais de Pairs Trading', color='white')
ax3.set_ylabel('Z-score')
ax3.legend(fontsize=9)
ax3.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('modelo4_cointegracion.png', dpi=150, bbox_inches='tight', facecolor='#050a14')
plt.show()

"""## dados importado acumulado do CDI"""

from bcb import sgs
import pandas as pd
import matplotlib.pyplot as plt

def get_accumulated_cdi(start_date: str, end_date: str) -> pd.DataFrame:
    """
    Fetches daily CDI rates from BCB API and calculates cumulative return.
    Dates must be in YYYY-MM-DD format.
    """
    #  CDI rates (Series 12)
    df = sgs.get({'cdi': 12}, start=start_date, end=end_date)

    # Convert percentages to absolute decimals (e.g., 0.05% -> 0.0005)
    df['daily_decimal'] = df['cdi'] / 100

    # Calculate geometric accumulation: Product of (1 + daily_rate)
    df['cdi_benchmark'] = (1 + df['daily_decimal']).cumprod() - 1

    # Convert benchmark back to a readable percentage format
    df['cdi_benchmark_pct'] = df['cdi_benchmark'] * 100

    return df[['cdi', 'cdi_benchmark_pct']]

# Calculate CDI performance
df_cdi = get_accumulated_cdi('2020-01-01', '2026-12-31')
print(df_cdi.tail())

plt.figure(figsize=(10, 6))
plt.plot(df_cdi.index, df_cdi['cdi_benchmark_pct'], marker='o', linestyle='--')
plt.title('Taxa CDI Anualizada')
plt.xlabel('Ano')
plt.ylabel('Taxa CDI')
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt

aligned_cdi = df_cdi['cdi_benchmark_pct'].reindex(cumulative_portfolio.index)

plt.figure(figsize=(12, 6))
plt.plot(cumulative_portfolio.index, cumulative_portfolio, label='Dinamic Portfolio (Cumulativo Return)', linewidth=2, color='blue')
plt.plot(aligned_cdi.index, aligned_cdi / 100 + 1, label='CDI (Cumulativo Return)', linestyle='--', color='green') # CDI is in percentage, convert to cumulative return factor

plt.title('Dinamic Portfolio vs. CDI Cumulativo Retorn')
plt.xlabel('Date')
plt.ylabel('Cumulativo Retorno ( $1)')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""
Portfólio Dinâmico: 23.07%
IBOV: 5.90%
S&P 500: 13.70%
CDI: 9.91%

Índice de Sharpe do Portfólio Dinâmico: 0.7734
Volatilidade Anualizada do Portfólio Dinâmico: 0.1549"""

import matplotlib.pyplot as plt
import pandas as pd

# Definir a data de início para normalização e plotagem
start_date_for_plot = '2023-01-01'

# --- 1. Preparar o Portfólio Dinâmico (Histórico + Simulado) ---

# Extrair a parte histórica normalizada do portfólio até o final do período de backtest
# `normalized_portfolio` já está normalizado para 1 em 2023-01-01 (de célula aa9a3fa5)
# `cumulative_portfolio` (do backtest) termina em 2025-12-31 (de célula XqK99Aaf-mAu)
norm_portfolio_hist_part = normalized_portfolio.loc[normalized_portfolio.index <= '2025-12-31']

# Encontrar o último valor normalizado do portfólio histórico e o valor bruto correspondente
last_normalized_val_hist = norm_portfolio_hist_part.iloc[-1]
last_cumulative_val_raw = cumulative_portfolio.iloc[-1] # Valor bruto no final do backtest

# Calcular o fator de escala para que a simulação continue perfeitamente da linha histórica normalizada
scaling_factor = last_normalized_val_hist / last_cumulative_val_raw

# Escalar os resultados da simulação de Monte Carlo
scaled_mean_simulated_path = mean_simulated_path * scaling_factor
scaled_lower_bound = lower_bound * scaling_factor
scaled_upper_bound = upper_bound * scaling_factor

# Combinar a parte histórica normalizada com a média da simulação escalada
combined_portfolio_full_path = pd.concat([norm_portfolio_hist_part, scaled_mean_simulated_path])

# --- 2. Preparar os Benchmarks (Históricos, normalizados para 2023-01-01) ---
# normalized_ibov, normalized_sp500, normalized_cdi já foram calculados e normalizados em aa9a3fa5
# e cobrem o período de 2023-01-01 até 2026-07-01.

# --- 3. Plotagem ---
plt.figure(figsize=(14, 7))

# Plotar o Portfólio Dinâmico (Histórico + Simulado)
plt.plot(combined_portfolio_full_path.index, combined_portfolio_full_path, label='Portfólio Dinâmico (Histórico + Simulado)', linewidth=2, color='blue')

# Preencher o intervalo de confiança para a parte simulada do portfólio
plt.fill_between(
    scaled_mean_simulated_path.index, # Usar o índice da parte simulada
    scaled_lower_bound,
    scaled_upper_bound,
    color='blue', alpha=0.1, label='Intervalo de Confiança (5%-95%) Simulado'
)

# Plotar os benchmarks históricos
plt.plot(normalized_ibov.index, normalized_ibov, label='IBOV (Histórico)', linestyle='--', color='red')
plt.plot(normalized_sp500.index, normalized_sp500, label='S&P 500 (Histórico)', linestyle='-.', color='purple')
plt.plot(normalized_cdi.index, normalized_cdi, label='CDI (Histórico)', linestyle=':', color='green')

plt.title('Comparação de Retorno Acumulado: Portfólio Dinâmico vs. Benchmarks (a partir de 2023)')
plt.xlabel('Data')
plt.ylabel('Retorno Acumulado (Crescimento de $1)')
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend()
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import yfinance as yf
import pandas as pd
import numpy as np

# Define end_date_overall (usando a data final do plot para consistência)
end_date_overall = '2026-07-01'

# 1. S&P500 Cumulative Returns
sp500_data_full = yf.download('^GSPC', start='2020-01-01', end=end_date_overall)['Close']
sp500_returns_full = sp500_data_full.pct_change().dropna()
cumulative_sp500_full_period = (1 + sp500_returns_full).cumprod()

# 2. CDI Cumulative Returns (assuming get_accumulated_cdi is defined elsewhere)
df_cdi_full_period = get_accumulated_cdi('2020-01-01', end_date_overall)
cumulative_cdi_full_period = (df_cdi_full_period['cdi_benchmark_pct'] / 100) + 1

# 3. IBOV Cumulative Returns (using ^BVSP)
ibov_data_full = yf.download('^BVSP', start='2020-01-01', end=end_date_overall)['Close']
ibov_returns_full = ibov_data_full.pct_change().dropna()
cumulative_ibov_full_period = (1 + ibov_returns_full).cumprod()

# 4. Dynamic Portfolio Cumulative Returns (from previous cell, e.g., XqK99Aaf-mAu)
dynamic_portfolio_cumulative_series = cumulative_portfolio

# Get the union of all unique dates from all series indices
all_dates = cumulative_ibov_full_period.index.union(
    cumulative_sp500_full_period.index
).union(
    cumulative_cdi_full_period.index
).union(
    dynamic_portfolio_cumulative_series.index
).sort_values()

# Reindex and fill NaNs for all series to the unified `all_dates` index
# This aligns all time series for consistent calculations and plotting.
aligned_dynamic_portfolio = dynamic_portfolio_cumulative_series.reindex(all_dates).fillna(1.0)
aligned_ibov = cumulative_ibov_full_period.reindex(all_dates).fillna(method='ffill').fillna(1.0)
aligned_sp500 = cumulative_sp500_full_period.reindex(all_dates).fillna(method='ffill').fillna(1.0)
aligned_cdi = cumulative_cdi_full_period.reindex(all_dates).fillna(method='ffill').fillna(1.0)

# Cálculo do Retorno Anualizado Acumulado

start_date_calc = all_dates.min()
end_date_calc = all_dates.max()
num_years = (end_date_calc - start_date_calc).days / 365.25

print(f"Período de cálculo de retorno anualizado: {start_date_calc.strftime('%Y-%m-%d')} a {end_date_calc.strftime('%Y-%m-%d')}\n")

# Retorno Anualizado para o Portfólio Dinâmico
# Usar o `dynamic_portfolio_cumulative_series` para o cálculo do retorno anualizado do portfólio dinâmico
# e ajustar `num_years` para o período real do portfólio dinâmico.
start_date_portfolio_actual = dynamic_portfolio_cumulative_series.index.min()
end_date_portfolio_actual = dynamic_portfolio_cumulative_series.index.max()
num_years_portfolio_actual = (end_date_portfolio_actual - start_date_portfolio_actual).days / 365.25

final_portfolio_return_actual = dynamic_portfolio_cumulative_series.iloc[-1]
initial_portfolio_return_actual = dynamic_portfolio_cumulative_series.iloc[0]
annualized_portfolio_return = (final_portfolio_return_actual / initial_portfolio_return_actual)**(1/num_years_portfolio_actual) - 1
print(f"Retorno Anualizado do Portfólio Dinâmico: {annualized_portfolio_return:.4f}")

# Retorno Anualizado para o IBOV
final_ibov_return = aligned_ibov.iloc[-1].item() # .item() para extrair o valor escalar de um Series
initial_ibov_return = aligned_ibov.iloc[0].item()
annualized_ibov_return = (final_ibov_return / initial_ibov_return)**(1/num_years) - 1
print(f"Retorno Anualizado do IBOV: {annualized_ibov_return:.4f}")

# Retorno Anualizado para o S&P 500
final_sp500_return = aligned_sp500.iloc[-1].item()
initial_sp500_return = aligned_sp500.iloc[0].item()
annualized_sp500_return = (final_sp500_return / initial_sp500_return)**(1/num_years) - 1
print(f"Retorno Anualizado do S&P 500: {annualized_sp500_return:.4f}")

# Retorno Anualizado para o CDI
final_cdi_return = aligned_cdi.iloc[-1].item()
initial_cdi_return = aligned_cdi.iloc[0].item()
annualized_cdi_return = (final_cdi_return / initial_cdi_return)**(1/num_years) - 1
print(f"Retorno Anualizado do CDI: {annualized_cdi_return:.4f}")

# Definir o período de interesse para o plot
start_plot_date = '2023-01-01'
end_plot_date = '2026-07-01'

# Filtrar os dados para o período de plotagem
filtered_portfolio = aligned_dynamic_portfolio.loc[start_plot_date:end_plot_date]
filtered_ibov = aligned_ibov.loc[start_plot_date:end_plot_date]
filtered_sp500 = aligned_sp500.loc[start_plot_date:end_plot_date]
filtered_cdi = aligned_cdi.loc[start_plot_date:end_plot_date]

# Normalizar os dados filtrados para que todos começem em 1 no início do período de plotagem
# Isso é importante para que o gráfico reflita corretamente o crescimento a partir de 2023
initial_val_portfolio = filtered_portfolio.iloc[0]
initial_val_ibov = filtered_ibov.iloc[0]
initial_val_sp500 = filtered_sp500.iloc[0]
initial_val_cdi = filtered_cdi.iloc[0]

normalized_portfolio = filtered_portfolio / initial_val_portfolio
normalized_ibov = filtered_ibov / initial_val_ibov
normalized_sp500 = filtered_sp500 / initial_val_sp500
normalized_cdi = filtered_cdi / initial_val_cdi

# plotar os retornos
plt.figure(figsize=(12, 6))
plt.plot(normalized_portfolio.index, normalized_portfolio, label='Portfólio Dinâmico (Retorno Acumulado)', linewidth=2, color='blue')
plt.plot(normalized_ibov.index, normalized_ibov, label='IBOV (Retorno Acumulado)', linestyle='--', color='red')
plt.plot(normalized_sp500.index, normalized_sp500, label='S&P 500 (Retorno Acumulado)', linestyle='-.', color='purple')
plt.plot(normalized_cdi.index, normalized_cdi, label='CDI (Retorno Acumulado)', linestyle=':', color='green')

plt.title('Comparação de Retorno Acumulado: Portfólio Dinâmico vs. IBOV, S&P 500 e CDI (2023-2026)')
plt.xlabel('Data')
plt.ylabel('Retorno Acumulado (Crescimento de $1)')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

print('-------SHARP PORTIFOLIO------')
sharpe_dynamic_portfolio = (dynamic_return_bt - Rf) / annualized_vol_bt
print(f"Índice de Sharpe do portfólio dinâmico: {sharpe_dynamic_portfolio:.4f}")

print('-------VOLATILIDADE PORTIFOLIO------')
sharpe_dynamic_portfolio = (dynamic_return_bt - Rf) / annualized_vol_bt
annualized_volatility_dynamic_portfolio = portfolio_returns_dynamic.std() * np.sqrt(TRADING_DAYS)
print(f"Volatilidade anualizada do portfólio dinâmico: {annualized_volatility_dynamic_portfolio:.4f}")

"""### Comparação dos Índices  Sharpe

resultados:

Sharpe Ratio do Portfólio Dinâmico: 0.7734
Sharpe Ratio do IBOV: 0.0980
Sharpe Ratio do S&P 500: 0.5846
Sharpe Ratio do CDI: 23.6636

O CDI apresenta um Sharpe Ratio significativamente mais alto, o que é esperado devido à sua menor volatilidade. Seu portfólio dinâmico tem um Sharpe Ratio mais alto que o IBOV e o S&P 500, indicando um bom desempenho ajustado ao risco em comparação com esses benchmarks de mercado de ações.
"""

TRADING_DAYS = 252 # Assumindo 252 dias de negociação por ano

# --- Volatilidade Anualizada dos Benchmarks ---

# Volatilidade Anualizada do IBOV
ibov_daily_returns_for_vol = ibov_data_full.pct_change().dropna()
annualized_volatility_ibov = ibov_daily_returns_for_vol.std().item() * np.sqrt(TRADING_DAYS)

# Volatilidade Anualizada do CDI
# Recalcular 'daily_decimal' a partir da coluna 'cdi' que está disponível em df_cdi_full_period
df_cdi_full_period['daily_decimal'] = df_cdi_full_period['cdi'] / 100
cdi_daily_returns_for_vol = df_cdi_full_period['daily_decimal'].dropna()
annualized_volatility_cdi = cdi_daily_returns_for_vol.std() * np.sqrt(TRADING_DAYS)

# Volatilidade Anualizada do S&P 500 (já calculada em `annualized_vol_benchmark`)
# annualized_vol_benchmark é uma Series, extrair o valor escalar
annualized_volatility_sp500 = annualized_vol_benchmark.item()


# --- Cálculo dos Índices de Sharpe para os Benchmarks ---

# Sharpe Ratio para o IBOV
sharpe_ibov = (annualized_ibov_return - Rf) / annualized_volatility_ibov

# Sharpe Ratio para o S&P 500 (Rf e annualized_sp500_return já estão disponíveis)
sharpe_sp500 = (annualized_sp500_return - Rf) / annualized_volatility_sp500

# Sharpe Ratio para o CDI
sharpe_cdi = (annualized_cdi_return - Rf) / annualized_volatility_cdi

# --- Exibir Resultados ---
print(f"Sharpe Ratio do Portfólio Dinâmico: {sharpe_dynamic_portfolio:.4f}")
print(f"Sharpe Ratio do IBOV: {sharpe_ibov:.4f}")
print(f"Sharpe Ratio do S&P 500: {sharpe_sp500:.4f}")
print(f"Sharpe Ratio do CDI: {sharpe_cdi:.4f}")

# Criar um DataFrame para melhor visualização
sharpe_comparison = pd.DataFrame({
    'Ativo': ['Portfólio Dinâmico', 'IBOV', 'S&P 500', 'CDI'],
    'Retorno Anualizado': [
        annualized_portfolio_return,
        annualized_ibov_return,
        annualized_sp500_return,
        annualized_cdi_return
    ],
    'Volatilidade Anualizada': [
        annualized_volatility_dynamic_portfolio,
        annualized_volatility_ibov,
        annualized_volatility_sp500,
        annualized_volatility_cdi
    ],
    'Sharpe Ratio': [
        sharpe_dynamic_portfolio,
        sharpe_ibov,
        sharpe_sp500,
        sharpe_cdi
    ]
})

display(sharpe_comparison.set_index('Ativo').sort_values(by='Sharpe Ratio', ascending=False))